"""
SQLGlot Parser Evaluation Tool

Purpose:
--------
Evaluate whether sqlglot can reliably parse the SQL generated by
our Enterprise Conversational AI Platform.

This is NOT a unit test.
This is an evaluation tool.

Run:
    python backend/tests/test_sqlglot_parser.py
"""

from sqlglot import parse_one
from sqlglot.errors import ParseError


TEST_QUERIES = [

    # ------------------------------------------------------------------
    # Simple SELECT
    # ------------------------------------------------------------------
    (
        "Simple SELECT",
        """
        SELECT Product, Sales
        FROM Sales
        """
    ),

    # ------------------------------------------------------------------
    # TOP
    # ------------------------------------------------------------------
    (
        "TOP",
        """
        SELECT TOP 10 Product, Sales
        FROM Sales
        ORDER BY Sales DESC
        """
    ),

    # ------------------------------------------------------------------
    # Aggregate
    # ------------------------------------------------------------------
    (
        "Aggregate",
        """
        SELECT Product,
               SUM(Sales) AS TotalSales
        FROM Sales
        GROUP BY Product
        """
    ),

    # ------------------------------------------------------------------
    # JOIN
    # ------------------------------------------------------------------
    (
        "JOIN",
        """
        SELECT
            S.Sales,
            P.Product
        FROM Sales S
        JOIN Products P
            ON S.ProductKey = P.ProductKey
        """
    ),

    # ------------------------------------------------------------------
    # WHERE
    # ------------------------------------------------------------------
    (
        "WHERE",
        """
        SELECT *
        FROM Sales
        WHERE Sales > 1000
        """
    ),

    # ------------------------------------------------------------------
    # GROUP BY + HAVING
    # ------------------------------------------------------------------
    (
        "HAVING",
        """
        SELECT Product,
               SUM(Sales)
        FROM Sales
        GROUP BY Product
        HAVING SUM(Sales) > 1000
        """
    ),

    # ------------------------------------------------------------------
    # ORDER BY
    # ------------------------------------------------------------------
    (
        "ORDER BY",
        """
        SELECT Product,
               Sales
        FROM Sales
        ORDER BY Sales DESC
        """
    ),

    # ------------------------------------------------------------------
    # Nested Query
    # ------------------------------------------------------------------
    (
        "Nested Query",
        """
        SELECT *
        FROM
        (
            SELECT Product,
                   Sales
            FROM Sales
        ) T
        """
    ),

    # ------------------------------------------------------------------
    # CTE
    # ------------------------------------------------------------------
    (
        "CTE",
        """
        WITH SalesCTE AS
        (
            SELECT *
            FROM Sales
        )

        SELECT *
        FROM SalesCTE
        """
    ),

    # ------------------------------------------------------------------
    # Invalid SQL
    # ------------------------------------------------------------------
    (
        "Invalid SQL",
        """
        SELECT FROM Sales
        """
    ),
    (
        "TOP",
        """
        SELECT TOP 10 PERCENT *
        FROM Sales
        """
    ),
    (
        "TOP WITH TIES",
        """
        SELECT TOP 5 WITH TIES *
        FROM Sales
        ORDER BY Sales DESC
        """
    ),
    (
        "Bracketed Identifiers",
        """
        SELECT [Product Name],
               [Sales Amount]
        FROM [Sales Table]
        """
    ),
    (
        "LEFT JOIN",
        """
        SELECT *
        FROM Sales S
        LEFT JOIN Products P
        ON S.ProductKey = P.ProductKey
        """
    ),
    (
        "Multiple JOINS",
        """
        SELECT *
        FROM Sales S
        JOIN Products P
ON S.ProductKey=P.ProductKey
JOIN Region R
ON S.RegionKey=R.RegionKey"""),
        (
        "Multiple JOINS",
        """
        SELECT *
        FROM Sales S
        JOIN Products P
ON S.ProductKey=P.ProductKey
JOIN Region R
ON S.RegionKey=R.RegionKey"""),
    (
        "UNION ALL",
        """
        SELECT Product
FROM Sales

UNION ALL

SELECT Product
FROM ArchiveSales"""),
    (
        "CASE",
        """
        SELECT
CASE
WHEN Sales>1000 THEN 'High'
ELSE 'Low'
END AS Category
FROM Sales"""),
(
    "Window Function",
    """
    SELECT
ROW_NUMBER() OVER(
PARTITION BY Region
ORDER BY Sales DESC
)
FROM Sales"""),
(
    "EXISTS",
    """
SELECT *
FROM Sales S
WHERE EXISTS
(
SELECT 1
FROM Products P
WHERE P.ProductKey=S.ProductKey
)
"""),
("SQL Injection Attempt","""
SELECT *
FROM Sales;
DROP TABLE Sales;""")
]


def evaluate_query(name: str, sql: str):

    print("=" * 80)
    print(name)
    print("=" * 80)

    try:

        ast = parse_one(sql, dialect="tsql")

        print("✅ PARSED SUCCESSFULLY\n")

        print("AST TYPE:")
        print(type(ast).__name__)

        print("\nNORMALIZED SQL:")
        print(ast.sql())

        print("\nAST TREE:")
        print(ast)
        print("\nDUMP:")
        print(ast.dump())

    except ParseError as e:

        print("❌ PARSE FAILED\n")
        print(e)

    except Exception as e:

        print("❌ UNKNOWN ERROR\n")
        print(type(e).__name__)
        print(e)

    print("\n\n")


def main():

    print("\n")
    print("#" * 80)
    print("SQLGLOT PARSER EVALUATION")
    print("#" * 80)
    print("\n")

    for name, sql in TEST_QUERIES:
        evaluate_query(name, sql)


if __name__ == "__main__":
    main()