CONNECTION_FAILED = "CONNECTION_FAILED"

SCHEMA_SYNC_FAILED = "SCHEMA_SYNC_FAILED"

RELATIONSHIP_DISCOVERY_FAILED = "RELATIONSHIP_DISCOVERY_FAILED"

SEMANTIC_DISCOVERY_FAILED = "SEMANTIC_DISCOVERY_FAILED"

DRIFT_DETECTION_FAILED = "DRIFT_DETECTION_FAILED"

UNKNOWN_ERROR = "UNKNOWN_ERROR"


from enum import Enum


class ErrorCode(str, Enum):

    CONNECTION_FAILED = "CONNECTION_FAILED"

    ENABLE_FAILED = "ENABLE_FAILED"

    SCHEMA_SYNC_FAILED = "SCHEMA_SYNC_FAILED"

    RELATIONSHIP_DISCOVERY_FAILED = "RELATIONSHIP_DISCOVERY_FAILED"

    SEMANTIC_DISCOVERY_FAILED = "SEMANTIC_DISCOVERY_FAILED"

    DRIFT_DETECTION_FAILED = "DRIFT_DETECTION_FAILED"

    VALIDATION_FAILED = "VALIDATION_FAILED"

    PERMISSION_DENIED = "PERMISSION_DENIED"

    UNKNOWN_ERROR = "UNKNOWN_ERROR"