from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional


@dataclass
class TableInfo:
    name: str
    alias: str | None = None


@dataclass
class ColumnInfo:
    name: str
    table: str | None = None
    alias: str | None = None


@dataclass
class JoinInfo:
    join_type: str
    table: str
    alias: str | None = None
    condition: str | None = None


@dataclass
class AggregateInfo:
    function: str
    column: str


@dataclass
class OrderByInfo:
    column: str
    direction: str


@dataclass
class PredicateInfo:
    expression: str


@dataclass
class WindowFunctionInfo:
    function: str


@dataclass
class SQLMetadata:
    tables: List[TableInfo] = field(default_factory=list)
    selected_columns: List[ColumnInfo] = field(default_factory=list)
    joins: List[JoinInfo] = field(default_factory=list)
    aggregates: List[AggregateInfo] = field(default_factory=list)
    group_by: List[str] = field(default_factory=list)
    order_by: List[OrderByInfo] = field(default_factory=list)
    where: List[PredicateInfo] = field(default_factory=list)
    having: List[PredicateInfo] = field(default_factory=list)
    ctes: List[str] = field(default_factory=list)
    window_functions: List[WindowFunctionInfo] = field(default_factory=list)
    subquery_count: int = 0
    limit: Optional[int] = None
    join_columns: List[ColumnInfo] = field(default_factory=list)
    where_columns: List[ColumnInfo] = field(default_factory=list)
    group_by_columns: List[ColumnInfo] = field(default_factory=list)
    having_columns: List[ColumnInfo] = field(default_factory=list)
    order_by_columns: List[ColumnInfo] = field(default_factory=list)
    cte_references: List[TableInfo] = field(default_factory=list)


@dataclass
class ValidationContext:
    """
    Carries all information through the SQL validation pipeline.
    Future phases will progressively populate this object.
    """

    # Original SQL generated by the LLM
    original_sql: str

    # Canonical SQL produced by sqlglot
    serialized_sql: Optional[str] = None

    # sqlglot AST object
    ast: Optional[Any] = None

    # Metadata extracted from AST (Phase 1)
    metadata: SQLMetadata = field(default_factory=SQLMetadata)

    # Validation diagnostics
    warnings: List[str] = field(default_factory=list)
    errors: List[str] = field(default_factory=list)

    # Future phases
    security_passed: bool = False
    schema_passed: bool = False
    execution_ready: bool = False