from enum import Enum


class TimeIntentType(str, Enum):
    UNKNOWN = "UNKNOWN"

    LAST_N_DAYS = "LAST_N_DAYS"
    LAST_N_WEEKS = "LAST_N_WEEKS"
    LAST_N_MONTHS = "LAST_N_MONTHS"
    LAST_N_YEARS = "LAST_N_YEARS"

    CURRENT_DAY = "CURRENT_DAY"
    CURRENT_WEEK = "CURRENT_WEEK"
    CURRENT_MONTH = "CURRENT_MONTH"
    CURRENT_YEAR = "CURRENT_YEAR"

    PREVIOUS_DAY = "PREVIOUS_DAY"
    PREVIOUS_WEEK = "PREVIOUS_WEEK"
    PREVIOUS_MONTH = "PREVIOUS_MONTH"
    PREVIOUS_YEAR = "PREVIOUS_YEAR"

    DATE_RANGE = "DATE_RANGE"
    YEAR_RANGE = "YEAR_RANGE"
    MONTH_RANGE = "MONTH_RANGE"

    YEAR_COMPARISON = "YEAR_COMPARISON"
    MONTH_COMPARISON = "MONTH_COMPARISON"

    YOY_GROWTH = "YOY_GROWTH"
    YOY_DEGROWTH = "YOY_DEGROWTH"

    TREND = "TREND"

    RUNNING_TOTAL = "RUNNING_TOTAL"

    YTD = "YTD"
    MTD = "MTD"
    QTD = "QTD"

    FISCAL_YTD = "FISCAL_YTD"

    CUSTOM = "CUSTOM"


class CalendarType(str, Enum):
    CALENDAR = "CALENDAR"
    FISCAL = "FISCAL"
    AUTO = "AUTO"


class Granularity(str, Enum):
    DAY = "DAY"
    WEEK = "WEEK"
    MONTH = "MONTH"
    QUARTER = "QUARTER"
    YEAR = "YEAR"
    AUTO = "AUTO"


class TimeStrategyType(str, Enum):
    DATE_COLUMN = "DATE_COLUMN"
    SNAPSHOT = "SNAPSHOT"
    CALENDAR_DIMENSION = "CALENDAR_DIMENSION"
    FISCAL = "FISCAL"
    DERIVED = "DERIVED"


class RelativeTimeDirection(str, Enum):
    LAST = "LAST"
    CURRENT = "CURRENT"
    NEXT = "NEXT"
    PREVIOUS = "PREVIOUS"
    ROLLING = "ROLLING"
    CUSTOM = "CUSTOM"


class StrategySelectionReason(str, Enum):
    SNAPSHOT_COLUMNS = "SNAPSHOT_COLUMNS"
    SNAPSHOT_PARTIAL = "SNAPSHOT_PARTIAL"
    SNAPSHOT_NON_OPTIMAL = "SNAPSHOT_NON_OPTIMAL"
    DATE_COLUMNS = "DATE_COLUMNS"
    CALENDAR_TABLE = "CALENDAR_TABLE"
    FINANCIAL_YEAR = "FINANCIAL_YEAR"
    DEFAULT_CALENDAR = "DEFAULT_CALENDAR"
    NO_MATCH = "NO_MATCH"
    PARTIAL_HISTORY = "PARTIAL_HISTORY"
    DERIVED = "DERIVED"
    CACHED = "CACHED"

